ERROR:app:Unhandled exception: 400 Bad Request: The CSRF token is invalid.
Traceback (most recent call last):
  File "/home/runner/SlideCheckAI/.pythonlibs/lib/python3.11/site-packages/flask_wtf/csrf.py", line 108, in validate_csrf
    token = s.loads(data, max_age=time_limit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/SlideCheckAI/.pythonlibs/lib/python3.11/site-packages/itsdangerous/timed.py", line 220, in loads
    raise t.cast(BadSignature, last_exception)
  File "/home/runner/SlideCheckAI/.pythonlibs/lib/python3.11/site-packages/itsdangerous/timed.py", line 204, in loads
    base64d, timestamp = signer.unsign(
                         ^^^^^^^^^^^^^^
  File "/home/runner/SlideCheckAI/.pythonlibs/lib/python3.11/site-packages/itsdangerous/timed.py", line 130, in unsign
    raise BadTimeSignature(str(sig_error), payload=value, date_signed=ts_dt)
itsdangerous.exc.BadTimeSignature: Signature b'lDS0wHQddlURFWB3dhZhTDINOz4' does not match

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/SlideCheckAI/.pythonlibs/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "/home/runner/SlideCheckAI/.pythonlibs/lib/python3.11/site-packages/flask_wtf/csrf.py", line 112, in validate_csrf
    raise ValidationError("The CSRF token is invalid.") from e
wtforms.validators.ValidationError: The CSRF token is invalid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/SlideCheckAI/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/SlideCheckAI/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/SlideCheckAI/.pythonlibs/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
    self.protect()
  File "/home/runner/SlideCheckAI/.pythonlibs/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "/home/runner/SlideCheckAI/.pythonlibs/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF token is invalid.
INFO:werkzeug:172.31.196.65 - - [28/Sep/2024 13:27:39] "POST / HTTP/1.1" 500 -